/*
 * Module initialisation for an H2Py extension module.
 *
 * The C file of an extension module is two lines:
 *
 *     #define H2PY_MODULE counter
 *     #include <h2py/init.h>
 *
 * which expand to a multi-phase PyInit_counter whose Py_mod_exec slot
 * initialises the GHC runtime on first use, registers the runtime hooks, and
 * calls h2py_hs_init_counter, the one foreign export that `pymodule`
 * generates.  PyInit_ must be C because it runs before hs_init; everything
 * after it is Haskell.
 *
 * Optional, defined before the include:
 *   H2PY_RTS_OPTS   a string of RTS options for this module, e.g. "-N"
 *   H2PY_MODULE_DOC the module docstring
 *
 * When compiled for the free-threaded stable ABI (H2PY_ABI3T), a
 * PyModExport_counter hook (PEP 793) is emitted as well, carrying the name,
 * doc and methods through slots, plus Py_mod_gil; both hooks may coexist and
 * CPython 3.15 prefers the new one.  Py_mod_gil must not appear in the abi3
 * slot array, because 3.12 rejects unknown slot ids at import.
 */
#ifndef H2PY_INIT_H
#define H2PY_INIT_H

#include <h2py/h2py.h>

#ifndef H2PY_MODULE
#  error "define H2PY_MODULE to the module name before including <h2py/init.h>"
#endif

#ifndef H2PY_RTS_OPTS
#  define H2PY_RTS_OPTS ""
#endif

#ifndef H2PY_MODULE_DOC
#  define H2PY_MODULE_DOC NULL
#endif

#define H2PY_CAT_(a, b) a##b
#define H2PY_CAT(a, b) H2PY_CAT_(a, b)
#define H2PY_STR_(x) #x
#define H2PY_STR(x) H2PY_STR_(x)

/* The foreign export generated by `pymodule`: fills the module object.
 * Returns 0, or -1 with a Python exception set. */
extern int H2PY_CAT(h2py_hs_init_, H2PY_MODULE)(PyObject *module);

/* Provided by the h2py library (cbits/rts_init.c). */
extern int h2py_hs_init(const char *module_opts);

static int H2PY_CAT(h2py_exec_, H2PY_MODULE)(PyObject *module)
{
    if (h2py_hs_init(H2PY_RTS_OPTS) < 0) {
        PyErr_SetString(h2py_exception_type(4), "H2Py: could not initialise the GHC runtime");
        return -1;
    }
    if (h2py_runtime_register_hooks(module) < 0) {
        return -1;
    }
    return H2PY_CAT(h2py_hs_init_, H2PY_MODULE)(module);
}

static PyModuleDef_Slot H2PY_CAT(h2py_slots_, H2PY_MODULE)[] = {
    {Py_mod_exec, (void *) H2PY_CAT(h2py_exec_, H2PY_MODULE)},
    {Py_mod_multiple_interpreters, Py_MOD_MULTIPLE_INTERPRETERS_NOT_SUPPORTED},
    {0, NULL},
};

static struct PyModuleDef H2PY_CAT(h2py_def_, H2PY_MODULE) = {
    PyModuleDef_HEAD_INIT,
    H2PY_STR(H2PY_MODULE),
    H2PY_MODULE_DOC,
    0,
    NULL,
    H2PY_CAT(h2py_slots_, H2PY_MODULE),
    NULL,
    NULL,
    NULL,
};

/* The symbol check runs before the module definition reaches CPython, whose
 * versions before 3.12 refuse its Py_mod_multiple_interpreters slot before any
 * exec slot could run. */
PyMODINIT_FUNC H2PY_CAT(PyInit_, H2PY_MODULE)(void)
{
    if (h2py_check_cpython_symbols() < 0) {
        return NULL;
    }
    return PyModuleDef_Init(&H2PY_CAT(h2py_def_, H2PY_MODULE));
}

#ifdef H2PY_ABI3T
/* PEP 793: the export hook has no PyModuleDef behind it, so the name, doc and
 * multiple-interpreter and GIL declarations travel as slots. */
static PyModuleDef_Slot H2PY_CAT(h2py_export_slots_, H2PY_MODULE)[] = {
    {Py_mod_name, (void *) H2PY_STR(H2PY_MODULE)},
#  ifdef H2PY_MODULE_DOC_STR
    {Py_mod_doc, (void *) H2PY_MODULE_DOC_STR},
#  endif
    {Py_mod_exec, (void *) H2PY_CAT(h2py_exec_, H2PY_MODULE)},
    {Py_mod_multiple_interpreters, Py_MOD_MULTIPLE_INTERPRETERS_NOT_SUPPORTED},
    {Py_mod_gil, Py_MOD_GIL_NOT_USED},
    {0, NULL},
};

PyMODINIT_FUNC H2PY_CAT(PyModExport_, H2PY_MODULE)(PyObject *spec)
{
    (void) spec;
    if (h2py_check_cpython_symbols() < 0) {
        return NULL;
    }
    return (PyObject *) H2PY_CAT(h2py_export_slots_, H2PY_MODULE);
}
#endif

#endif /* H2PY_INIT_H */
