/* Generated by scripts/gen-weakapi.sh; do not edit by hand.
 *
 * Every CPython symbol the h2py library references, marked as a weak
 * reference: the library must be loadable by GHC, with no interpreter in
 * the process, to run Template Haskell splices, and the references bind
 * to the interpreter as usual once an extension module is imported.
 * dyld binds every symbol at load time on macOS, and on Linux a function
 * whose address the shim takes needs its symbol at load time too.
 * Included by <h2py/h2py.h> after <Python.h>; a pragma for a symbol that
 * is not referenced is harmless, so the list only grows. */
#ifndef H2PY_WEAKAPI_H
#define H2PY_WEAKAPI_H
#pragma weak PyBool_FromLong
#pragma weak PyBuffer_Release
#pragma weak PyBytes_AsStringAndSize
#pragma weak PyBytes_FromStringAndSize
#pragma weak PyCallable_Check
#pragma weak PyDict_New
#pragma weak PyDict_Next
#pragma weak PyDict_SetItem
#pragma weak PyDict_SetItemString
#pragma weak PyDict_Size
#pragma weak PyErr_CheckSignals
#pragma weak PyErr_Clear
#pragma weak PyErr_Format
#pragma weak PyErr_GetRaisedException
#pragma weak PyErr_NewException
#pragma weak PyErr_NoMemory
#pragma weak PyErr_Occurred
#pragma weak PyErr_SetObject
#pragma weak PyErr_SetRaisedException
#pragma weak PyErr_SetString
#pragma weak PyErr_WriteUnraisable
#pragma weak PyEval_RestoreThread
#pragma weak PyEval_SaveThread
#pragma weak PyFloat_AsDouble
#pragma weak PyFloat_FromDouble
#pragma weak PyGILState_Ensure
#pragma weak PyGILState_GetThisThreadState
#pragma weak PyGILState_Release
#pragma weak PyImport_GetModuleDict
#pragma weak PyImport_ImportModule
#pragma weak PyIter_Next
#pragma weak PyList_Append
#pragma weak PyList_New
#pragma weak PyList_SetItem
#pragma weak PyLong_AsLongLong
#pragma weak PyLong_FromLongLong
#pragma weak PyLong_FromString
#pragma weak PyMapping_Check
#pragma weak PyMapping_Items
#pragma weak PyMemoryView_FromObject
#pragma weak PyModule_AddFunctions
#pragma weak PyModule_AddObjectRef
#pragma weak PyModule_GetNameObject
#pragma weak PyModule_New
#pragma weak PyNumber_Index
#pragma weak PyNumber_Long
#pragma weak PyNumber_ToBase
#pragma weak PyObject_Call
#pragma weak PyObject_CallMethod
#pragma weak PyObject_CallNoArgs
#pragma weak PyObject_DelItem
#pragma weak PyObject_Free
#pragma weak PyObject_GetAttr
#pragma weak PyObject_GetAttrString
#pragma weak PyObject_GetBuffer
#pragma weak PyObject_GetItem
#pragma weak PyObject_GetIter
#pragma weak PyObject_GetTypeData
#pragma weak PyObject_HasAttrString
#pragma weak PyObject_Hash
#pragma weak PyObject_HashNotImplemented
#pragma weak PyObject_IsInstance
#pragma weak PyObject_IsSubclass
#pragma weak PyObject_IsTrue
#pragma weak PyObject_Length
#pragma weak PyObject_Repr
#pragma weak PyObject_RichCompare
#pragma weak PyObject_RichCompareBool
#pragma weak PyObject_SetAttrString
#pragma weak PyObject_SetItem
#pragma weak PyObject_Size
#pragma weak PyObject_Str
#pragma weak PyObject_Type
#pragma weak PyObject_Vectorcall
#pragma weak PySequence_Check
#pragma weak PySequence_GetItem
#pragma weak PySequence_Size
#pragma weak PySet_Add
#pragma weak PySet_New
#pragma weak PyTuple_GetItem
#pragma weak PyTuple_New
#pragma weak PyTuple_SetItem
#pragma weak PyTuple_Size
#pragma weak PyType_FromModuleAndSpec
#pragma weak PyType_FromSpec
#pragma weak PyType_GenericAlloc
#pragma weak PyType_GetSlot
#pragma weak PyType_IsSubtype
#pragma weak PyUnicode_AsUTF8AndSize
#pragma weak PyUnicode_FromStringAndSize
#pragma weak Py_DecRef
#pragma weak Py_IncRef

#ifdef H2PY_WEAKAPI_TABLE
/* Every symbol above with its address, which is NULL when the interpreter
 * lacks it; h2py.c defines H2PY_WEAKAPI_TABLE and checks the table when
 * a module is imported (h2py_check_cpython_symbols). */
static const struct {
    const char *name;
    const void *address;
} h2py_weakapi_table[] = {
    {"PyBool_FromLong", (const void *) &PyBool_FromLong},
    {"PyBuffer_Release", (const void *) &PyBuffer_Release},
    {"PyBytes_AsStringAndSize", (const void *) &PyBytes_AsStringAndSize},
    {"PyBytes_FromStringAndSize", (const void *) &PyBytes_FromStringAndSize},
    {"PyCallable_Check", (const void *) &PyCallable_Check},
    {"PyDict_New", (const void *) &PyDict_New},
    {"PyDict_Next", (const void *) &PyDict_Next},
    {"PyDict_SetItem", (const void *) &PyDict_SetItem},
    {"PyDict_SetItemString", (const void *) &PyDict_SetItemString},
    {"PyDict_Size", (const void *) &PyDict_Size},
    {"PyErr_CheckSignals", (const void *) &PyErr_CheckSignals},
    {"PyErr_Clear", (const void *) &PyErr_Clear},
    {"PyErr_Format", (const void *) &PyErr_Format},
    {"PyErr_GetRaisedException", (const void *) &PyErr_GetRaisedException},
    {"PyErr_NewException", (const void *) &PyErr_NewException},
    {"PyErr_NoMemory", (const void *) &PyErr_NoMemory},
    {"PyErr_Occurred", (const void *) &PyErr_Occurred},
    {"PyErr_SetObject", (const void *) &PyErr_SetObject},
    {"PyErr_SetRaisedException", (const void *) &PyErr_SetRaisedException},
    {"PyErr_SetString", (const void *) &PyErr_SetString},
    {"PyErr_WriteUnraisable", (const void *) &PyErr_WriteUnraisable},
    {"PyEval_RestoreThread", (const void *) &PyEval_RestoreThread},
    {"PyEval_SaveThread", (const void *) &PyEval_SaveThread},
    {"PyFloat_AsDouble", (const void *) &PyFloat_AsDouble},
    {"PyFloat_FromDouble", (const void *) &PyFloat_FromDouble},
    {"PyGILState_Ensure", (const void *) &PyGILState_Ensure},
    {"PyGILState_GetThisThreadState", (const void *) &PyGILState_GetThisThreadState},
    {"PyGILState_Release", (const void *) &PyGILState_Release},
    {"PyImport_GetModuleDict", (const void *) &PyImport_GetModuleDict},
    {"PyImport_ImportModule", (const void *) &PyImport_ImportModule},
    {"PyIter_Next", (const void *) &PyIter_Next},
    {"PyList_Append", (const void *) &PyList_Append},
    {"PyList_New", (const void *) &PyList_New},
    {"PyList_SetItem", (const void *) &PyList_SetItem},
    {"PyLong_AsLongLong", (const void *) &PyLong_AsLongLong},
    {"PyLong_FromLongLong", (const void *) &PyLong_FromLongLong},
    {"PyLong_FromString", (const void *) &PyLong_FromString},
    {"PyMapping_Check", (const void *) &PyMapping_Check},
    {"PyMapping_Items", (const void *) &PyMapping_Items},
    {"PyMemoryView_FromObject", (const void *) &PyMemoryView_FromObject},
    {"PyModule_AddFunctions", (const void *) &PyModule_AddFunctions},
    {"PyModule_AddObjectRef", (const void *) &PyModule_AddObjectRef},
    {"PyModule_GetNameObject", (const void *) &PyModule_GetNameObject},
    {"PyModule_New", (const void *) &PyModule_New},
    {"PyNumber_Index", (const void *) &PyNumber_Index},
    {"PyNumber_Long", (const void *) &PyNumber_Long},
    {"PyNumber_ToBase", (const void *) &PyNumber_ToBase},
    {"PyObject_Call", (const void *) &PyObject_Call},
    {"PyObject_CallMethod", (const void *) &PyObject_CallMethod},
    {"PyObject_CallNoArgs", (const void *) &PyObject_CallNoArgs},
    {"PyObject_DelItem", (const void *) &PyObject_DelItem},
    {"PyObject_Free", (const void *) &PyObject_Free},
    {"PyObject_GetAttr", (const void *) &PyObject_GetAttr},
    {"PyObject_GetAttrString", (const void *) &PyObject_GetAttrString},
    {"PyObject_GetBuffer", (const void *) &PyObject_GetBuffer},
    {"PyObject_GetItem", (const void *) &PyObject_GetItem},
    {"PyObject_GetIter", (const void *) &PyObject_GetIter},
    {"PyObject_GetTypeData", (const void *) &PyObject_GetTypeData},
    {"PyObject_HasAttrString", (const void *) &PyObject_HasAttrString},
    {"PyObject_Hash", (const void *) &PyObject_Hash},
    {"PyObject_HashNotImplemented", (const void *) &PyObject_HashNotImplemented},
    {"PyObject_IsInstance", (const void *) &PyObject_IsInstance},
    {"PyObject_IsSubclass", (const void *) &PyObject_IsSubclass},
    {"PyObject_IsTrue", (const void *) &PyObject_IsTrue},
    {"PyObject_Length", (const void *) &PyObject_Length},
    {"PyObject_Repr", (const void *) &PyObject_Repr},
    {"PyObject_RichCompare", (const void *) &PyObject_RichCompare},
    {"PyObject_RichCompareBool", (const void *) &PyObject_RichCompareBool},
    {"PyObject_SetAttrString", (const void *) &PyObject_SetAttrString},
    {"PyObject_SetItem", (const void *) &PyObject_SetItem},
    {"PyObject_Size", (const void *) &PyObject_Size},
    {"PyObject_Str", (const void *) &PyObject_Str},
    {"PyObject_Type", (const void *) &PyObject_Type},
    {"PyObject_Vectorcall", (const void *) &PyObject_Vectorcall},
    {"PySequence_Check", (const void *) &PySequence_Check},
    {"PySequence_GetItem", (const void *) &PySequence_GetItem},
    {"PySequence_Size", (const void *) &PySequence_Size},
    {"PySet_Add", (const void *) &PySet_Add},
    {"PySet_New", (const void *) &PySet_New},
    {"PyTuple_GetItem", (const void *) &PyTuple_GetItem},
    {"PyTuple_New", (const void *) &PyTuple_New},
    {"PyTuple_SetItem", (const void *) &PyTuple_SetItem},
    {"PyTuple_Size", (const void *) &PyTuple_Size},
    {"PyType_FromModuleAndSpec", (const void *) &PyType_FromModuleAndSpec},
    {"PyType_FromSpec", (const void *) &PyType_FromSpec},
    {"PyType_GenericAlloc", (const void *) &PyType_GenericAlloc},
    {"PyType_GetSlot", (const void *) &PyType_GetSlot},
    {"PyType_IsSubtype", (const void *) &PyType_IsSubtype},
    {"PyUnicode_AsUTF8AndSize", (const void *) &PyUnicode_AsUTF8AndSize},
    {"PyUnicode_FromStringAndSize", (const void *) &PyUnicode_FromStringAndSize},
    {"Py_DecRef", (const void *) &Py_DecRef},
    {"Py_IncRef", (const void *) &Py_IncRef},
};
#endif /* H2PY_WEAKAPI_TABLE */
#endif /* H2PY_WEAKAPI_H */
