/* Generated by scripts/gen-weakapi.sh; do not edit by hand.
 *
 * Every CPython symbol the h2py library references, marked as a weak
 * reference on macOS: the library must be loadable by GHC, with no
 * interpreter in the process, to run Template Haskell splices, and the
 * references bind to the interpreter as usual once an extension module is
 * imported.  Included by <h2py/h2py.h> after <Python.h>; a pragma for a
 * symbol that is not referenced is harmless, so the list only grows. */
#ifndef H2PY_WEAKAPI_H
#define H2PY_WEAKAPI_H
#ifdef __APPLE__
#pragma weak PyBool_FromLong
#pragma weak PyBuffer_Release
#pragma weak PyBytes_AsStringAndSize
#pragma weak PyBytes_FromStringAndSize
#pragma weak PyCallable_Check
#pragma weak PyDict_New
#pragma weak PyDict_Next
#pragma weak PyDict_SetItem
#pragma weak PyDict_SetItemString
#pragma weak PyDict_Size
#pragma weak PyErr_CheckSignals
#pragma weak PyErr_Clear
#pragma weak PyErr_Format
#pragma weak PyErr_GetRaisedException
#pragma weak PyErr_NewException
#pragma weak PyErr_NoMemory
#pragma weak PyErr_Occurred
#pragma weak PyErr_SetObject
#pragma weak PyErr_SetRaisedException
#pragma weak PyErr_SetString
#pragma weak PyErr_WriteUnraisable
#pragma weak PyEval_RestoreThread
#pragma weak PyEval_SaveThread
#pragma weak PyFloat_AsDouble
#pragma weak PyFloat_FromDouble
#pragma weak PyGILState_Ensure
#pragma weak PyGILState_GetThisThreadState
#pragma weak PyGILState_Release
#pragma weak PyImport_GetModuleDict
#pragma weak PyImport_ImportModule
#pragma weak PyIter_Next
#pragma weak PyList_Append
#pragma weak PyList_New
#pragma weak PyList_SetItem
#pragma weak PyLong_AsLongLong
#pragma weak PyLong_FromLongLong
#pragma weak PyLong_FromString
#pragma weak PyMapping_Check
#pragma weak PyMapping_Items
#pragma weak PyMemoryView_FromObject
#pragma weak PyModule_AddFunctions
#pragma weak PyModule_AddObjectRef
#pragma weak PyModule_GetNameObject
#pragma weak PyModule_New
#pragma weak PyNumber_Index
#pragma weak PyNumber_Long
#pragma weak PyNumber_ToBase
#pragma weak PyObject_Call
#pragma weak PyObject_CallMethod
#pragma weak PyObject_CallNoArgs
#pragma weak PyObject_DelItem
#pragma weak PyObject_Free
#pragma weak PyObject_GetAttr
#pragma weak PyObject_GetAttrString
#pragma weak PyObject_GetBuffer
#pragma weak PyObject_GetItem
#pragma weak PyObject_GetIter
#pragma weak PyObject_GetTypeData
#pragma weak PyObject_HasAttrString
#pragma weak PyObject_Hash
#pragma weak PyObject_HashNotImplemented
#pragma weak PyObject_IsInstance
#pragma weak PyObject_IsSubclass
#pragma weak PyObject_IsTrue
#pragma weak PyObject_Length
#pragma weak PyObject_Repr
#pragma weak PyObject_RichCompare
#pragma weak PyObject_RichCompareBool
#pragma weak PyObject_SetAttrString
#pragma weak PyObject_SetItem
#pragma weak PyObject_Size
#pragma weak PyObject_Str
#pragma weak PyObject_Type
#pragma weak PyObject_Vectorcall
#pragma weak PySequence_Check
#pragma weak PySequence_GetItem
#pragma weak PySequence_Size
#pragma weak PySet_Add
#pragma weak PySet_New
#pragma weak PyTuple_GetItem
#pragma weak PyTuple_New
#pragma weak PyTuple_SetItem
#pragma weak PyTuple_Size
#pragma weak PyType_FromModuleAndSpec
#pragma weak PyType_FromSpec
#pragma weak PyType_GenericAlloc
#pragma weak PyType_GetSlot
#pragma weak PyType_IsSubtype
#pragma weak PyUnicode_AsUTF8AndSize
#pragma weak PyUnicode_FromStringAndSize
#pragma weak Py_DecRef
#pragma weak Py_IncRef
#endif /* __APPLE__ */
#endif /* H2PY_WEAKAPI_H */
