# h2py_examples.pyi, generated by H2Py; do not edit.
from typing import Any, Iterator

def add(x: int, y: int) -> int:
    """Add two integers."""

class Counter:
    """A counter whose state lives in the Haskell heap."""
    def __init__(self, n: int) -> None: ...
    def incr(self, k: int) -> None:
        """Add k to the counter."""
    def get(self) -> int:
        """The current value."""
    def label(self) -> str:
        ...

class HsIterator:
    """An iterator whose state lives in the Haskell heap."""
    def __next__(self) -> Any:
        ...
    def __iter__(self) -> HsIterator:
        ...


# submodule h2py_examples.nparallel: see nparallel.pyi


# submodule h2py_examples.shapes: see shapes.pyi


# submodule h2py_examples.concurrency: see concurrency.pyi


# submodule h2py_examples.ops: see ops.pyi


# submodule h2py_examples.tutorial: see tutorial.pyi

