# concurrency.pyi, generated by H2Py; do not edit.
from typing import Any, Iterator

def sleep_detached(seconds: float) -> None:
    """Sleep with the interpreter released."""

def par_sum(xs: list[int]) -> int:
    """Sum a list, the two halves in parallel with the interpreter released."""

def par_call(f: Any, g: Any) -> tuple[Any, ...]:
    """Call f and g in parPy branches and return (f(), g())."""

def par_bio_error() -> int:
    """detach (parBIO ...) with a branch that calls error: raises RuntimeError."""

def lazy_error_detached() -> int:
    """Force a lazy ValueError on a detached thread and raise it."""

def call_from_unattached_thread(o: Any) -> bool:
    """True when a Python operation from an unbound Haskell thread raised NotAttached."""

def loop_with_scopes(n: int) -> int:
    """Create n strings, one per attach'_ scope; returns n."""

def interruptible_loop(n: int) -> int:
    """Loop n times checking signals; raises KeyboardInterrupt when one is pending."""

def sleep_then_check(seconds: float) -> bool:
    """Sleep detached, then check signals; True when a KeyboardInterrupt was pending."""

def nested_attach_in_method() -> int:
    """Detach and attach afresh on the calling thread; the length of a string built inside."""

class SharedCounter:
    """A counter whose methods can hold their payload across a detached wait."""
    def __init__(self, n: int) -> None: ...
    def incr(self, k: int) -> None:
        """Add k to the counter."""
    def get(self) -> int:
        """The current value."""
    def hold_mut(self, seconds: float) -> int:
        """Hold the payload mutably across a detached sleep, then add one."""
    def hold_share(self, seconds: float) -> int:
        """Hold the payload shared across a detached sleep."""
    def nested_attach_in_method(self) -> int:
        """Detach and attach afresh inside a method."""

class Series:
    """A vector of integers whose long methods run with the interpreter released."""
    def __init__(self, xs: list[int]) -> None: ...
    def total(self) -> int:
        """The sum of the elements, attached."""
    def scale(self, k: int) -> None:
        """Multiply every element by k, attached."""
    def hold_share_bio(self, seconds: float) -> int:
        """A BIO body on a Share receiver: sleep detached, then sum."""
    def scale_bio(self, k: int, seconds: float) -> None:
        """A BIO body on a Mut receiver: sleep detached, then multiply in place."""
    def total_detached(self, reps: int) -> int:
        """A BO body registered detached: the sum taken reps times."""

