# nparallel.pyi, generated by H2Py; do not edit.
from typing import Any, Iterator
import collections.abc
import numpy
import numpy.typing

def sort_in_place(arr: numpy.typing.NDArray[numpy.float64]) -> None:
    """Sort a float64 array in place with a parallel quicksort, the interpreter released."""

def fft(arr: numpy.typing.NDArray[numpy.complex128]) -> None:
    """The discrete Fourier transform of a complex128 array in place, as numpy.fft.fft computes it, with a parallel radix-2 FFT; the length must be a power of two (ValueError otherwise)."""

def stencil(arr: numpy.typing.NDArray[numpy.float64]) -> None:
    """A three-point moving average of a float64 array in place, zero beyond the ends, the two halves in parallel: numpy.convolve(arr, numpy.ones(3) / 3, mode='same')."""

def sum(arr: numpy.typing.NDArray[numpy.float64]) -> float:
    """The sum of a float64 array, read through a shared buffer view, two halves in parallel."""

def scale_in_place(arr: numpy.typing.NDArray[numpy.float64], k: float) -> None:
    """Multiply every element of a float64 array by k in place, two halves in parallel."""

def iota(n: int) -> collections.abc.Buffer:
    """A Haskell-owned float64 array [0, 1, ..., n - 1] that numpy.asarray wraps without a copy."""

