# ops.pyi, generated by H2Py; do not edit.
from typing import Any, Iterator

def get_attr(o: Any, name: str) -> Any:
    ...

def set_attr(o: Any, name: str, v: Any) -> None:
    ...

def get_item(o: Any, k: Any) -> Any:
    ...

def set_item(o: Any, k: Any, v: Any) -> None:
    ...

def del_item(o: Any, k: Any) -> None:
    ...

def length(o: Any) -> int:
    ...

def repr_(o: Any) -> str:
    ...

def str_(o: Any) -> str:
    ...

def call(f: Any, args: list[Any]) -> Any:
    ...

def iterate_sum(iterable: Any) -> int:
    ...

def hash_(o: Any) -> int:
    ...

def equals(a: Any, b: Any) -> bool:
    ...

def downcast_int(o: Any) -> bool:
    ...

def roundtrip_int(arg0: int, /) -> int:
    ...

def roundtrip_integer(arg0: int, /) -> int:
    ...

def roundtrip_word(arg0: int, /) -> int:
    ...

def roundtrip_double(arg0: float, /) -> float:
    ...

def roundtrip_float(arg0: float, /) -> float:
    ...

def roundtrip_bool(arg0: bool, /) -> bool:
    ...

def roundtrip_char(arg0: str, /) -> str:
    ...

def roundtrip_text(arg0: str, /) -> str:
    ...

def roundtrip_string(arg0: str, /) -> str:
    ...

def roundtrip_bytes(arg0: bytes, /) -> bytes:
    ...

def roundtrip_unit(arg0: None, /) -> None:
    ...

def roundtrip_maybe_int(arg0: int | None, /) -> int | None:
    ...

def roundtrip_either_int_text(arg0: int | str, /) -> int | str:
    ...

def roundtrip_int_list(arg0: list[int], /) -> list[int]:
    ...

def roundtrip_double_vector(arg0: list[float], /) -> list[float]:
    ...

def map_items(arg0: dict[str, int], /) -> list[tuple[str, int]]:
    ...

def set_items(arg0: set[int], /) -> list[int]:
    ...

def roundtrip_tuple2(arg0: tuple[int, str], /) -> tuple[int, str]:
    ...

def roundtrip_tuple3(arg0: tuple[int, str, float], /) -> tuple[int, str, float]:
    ...

def roundtrip_tuple4(arg0: tuple[int, str, float, bool], /) -> tuple[int, str, float, bool]:
    ...

def roundtrip_tuple5(arg0: tuple[int, str, float, bool, list[int]], /) -> tuple[int, str, float, bool, list[int]]:
    ...

def big_integer() -> int:
    ...

def stash(o: Any) -> None:
    ...

def stashed() -> Any | None:
    ...

def unstash() -> None:
    ...

def haskell_gc() -> None:
    ...

def noop() -> None:
    ...

def fail_value_error() -> None:
    ...

def fail_type_error() -> int:
    ...

def haskell_error() -> int:
    ...

def use_then_error(o: Any) -> int:
    ...

def use_mut_then_error(o: Any, name: str, v: Any) -> int:
    ...

def throw_on_left() -> int:
    ...

def key_error_roundtrip() -> None:
    ...

def has_attr(o: Any, name: str) -> bool:
    ...

def del_attr(o: Any, name: str) -> None:
    ...

def get_index(o: Any, i: int) -> Any:
    ...

def is_true(o: Any) -> bool:
    ...

def call0(f: Any) -> Any:
    ...

def call_method(o: Any, name: str, args: list[Any]) -> Any:
    ...

def call_method0(o: Any, name: str) -> Any:
    ...

def rich_compare(a: Any, op: int, b: Any) -> bool:
    ...

def type_of(o: Any) -> type:
    ...

def downcast_mut_int(o: Any) -> int:
    ...

def list_append(lst: list[Any], v: Any) -> None:
    ...

def set_add(s: set[Any], v: Any) -> None:
    ...

def to_str(arg0: str, /) -> str:
    ...

def to_bytes(arg0: bytes, /) -> bytes:
    ...

def to_int(arg0: int, /) -> int:
    ...

def to_integer(arg0: int, /) -> int:
    ...

def to_float(arg0: float, /) -> float:
    ...

def to_bool(arg0: bool, /) -> bool:
    ...

def none_() -> None:
    ...

def to_list(iterable: Any) -> list[Any]:
    ...

def to_tuple(iterable: Any) -> tuple[Any, ...]:
    ...

def empty_tuple() -> tuple[Any, ...]:
    ...

def to_dict(pairs: Any) -> dict[Any, Any]:
    ...

def to_set(iterable: Any) -> set[Any]:
    ...

def new_dict() -> dict[Any, Any]:
    ...

def new_list() -> list[Any]:
    ...

def copy_out_int(arg0: int, /) -> int:
    ...

def copy_out_float(arg0: float, /) -> float:
    ...

def copy_out_bool(arg0: bool, /) -> bool:
    ...

def copy_out_str(arg0: str, /) -> str:
    ...

def copy_out_bytes(arg0: bytes, /) -> bytes:
    ...

def copy_out_none(arg0: None, /) -> None:
    ...

def handle_roundtrip(o: Any) -> Any:
    ...

def ghost_arg(g: Any) -> None:
    """Takes an instance of the unregistered Ghost class."""

def make_ghost() -> Any:
    """Construct an instance of the unregistered Ghost class."""

def make_unsealed() -> None:
    """Construct an instance of a class whose hand-written instance lacks the sealed witness."""

class Cell:
    """A cell whose integer lives in a Haskell Ref."""
    def __init__(self, n: int) -> None: ...
    def get(self) -> int:
        """The current value."""
    def incr(self, k: int) -> None:
        """Add k."""
    def incr_then_fail(self, k: int) -> None:
        """Add k, then fail with ValueError; the cell stays usable."""
    def poison(self) -> None:
        """Raise a Haskell error while the payload is held mutably: poisons the cell."""
    def sum_with(self, other: Cell) -> int:
        """The sum of this cell and another."""
    def identity(self) -> Cell:
        """Return self."""
    def call_while_held(self, f: Any) -> Any:
        """Call f() while the payload is held mutably, then add one."""
    def deref_second(self, other: Cell) -> int:
        """Dereference another handle mutably while this payload is held."""
    def hold_until_timeout(self, seconds: float) -> int:
        """Hold the payload detached until a timeout interrupts the wait: poisons the cell."""
    def hold_until_killed(self, seconds: float) -> int:
        """Hold the payload detached until an asynchronous exception arrives: poisons the cell."""
    def scoped_hold(self) -> int:
        """Add one inside an attach'_ scope, then read through the receiver after it."""

class Helper:
    """A helper made inside another constructor."""
    def value(self) -> int:
        """The value the helper was made with."""

class Base:
    """A subclassable class whose constructor makes helpers."""
    def __init__(self) -> None: ...
    def helper(self) -> Helper:
        """The helper made in the constructor's arena."""
    def scoped_helper(self) -> Helper:
        """The helper made inside an attach'_ scope of the constructor."""

