{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE ImpredicativeTypes #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -Wno-redundant-constraints #-}
{-# OPTIONS_HADDOCK hide #-}

{- |
Python classes with Haskell payloads.

The Haskell payload type /is/ the Python type tag, so an instance of the class
@Counter@ is @'Bound' π Counter@.
The object holds a stable pointer to the payload and one word of lend state,
PyO3's borrow flag, in type data reached through @PyObject_GetTypeData@.
A dereference turns a borrow of the object into a borrow of its payload, in
place, at the ambient lifetime, and the hold it takes is released when the
arena that took it is swept.
See section 5.3 of the design.
-}
module H2Py.Class.Internal (
  module H2Py.Class.Internal,
) where

import Control.Exception (SomeException, evaluate, finally, mask, throwIO, try)
import Control.Functor.Linear qualified as Control
import Control.Monad qualified as NonLinear
import Control.Monad.Borrow.BO (Mut, Share, share, type (>=))
import Control.Monad.Borrow.Copyable (Copyable (..))
import Control.Monad.Borrow.Lifetime.Internal (Lifetime)
import Control.Monad.Borrow.Unsafe (Alias (..))
import Data.IORef (IORef, newIORef, readIORef, writeIORef)
import Data.Kind (Type)
import Data.Proxy (Proxy (..))
import Data.Text (Text)
import Data.Text qualified as T
import Foreign.C.Types (CInt (..))
import Foreign.Ptr (Ptr, castPtr, nullPtr)
import Foreign.StablePtr (StablePtr, castPtrToStablePtr, castStablePtrToPtr, deRefStablePtr, freeStablePtr, newStablePtr)
import H2Py.Exception.Internal (someExceptionToPyErr)
import H2Py.Object.Internal
import H2Py.Py.Internal
import H2Py.Runtime.Internal
import Prelude.Linear (Consumable (..), Movable (..), Ur (..))
import Unsafe.Linear qualified as Unsafe

{- | The type object of a class, filled in by module initialisation.
One per class, generated by @pyclass@ as a top-level @NOINLINE@ cell.
-}
newtype TypeCell = TypeCell (IORef (Ptr PyObject))
  deriving stock (Eq)

-- | Allocate a cell; only ever called from a @NOINLINE@ top-level binding that @pyclass@ generates.
newTypeCell :: IO TypeCell
newTypeCell = TypeCell <$> newIORef nullPtr

-- | Read the type object of a class; 'nullPtr' before the module is initialised.
readTypeCell :: TypeCell -> IO (Ptr PyObject)
readTypeCell (TypeCell ref) = readIORef ref

-- | Record the type object once it exists.
writeTypeCell :: TypeCell -> Ptr PyObject -> IO ()
writeTypeCell (TypeCell ref) = writeIORef ref

{- | A Python class whose instances carry a Haskell payload of type @a@.

Instances are generated by @pyclass ''T@, which also checks that @T@ is closed:
a payload type with a parameter is refused, because a parameterised instance
would let a stored reference's attachment unify with a later call's.
A hand-written instance carries that obligation.
-}
class (Consumable a) => PyClass a where
  -- | The Python name of the class.
  pyClassName :: Proxy a -> Text

  -- | The docstring.
  pyClassDoc :: Proxy a -> Text
  pyClassDoc _ = ""

  -- | The cell holding the type object.
  pyClassTypeCell :: Proxy a -> TypeCell

  -- | The witness that the instance is trusted; see Note [Sealed classes] in "H2Py.Object.Internal".
  pyClassSealed :: Proxy a -> Sealed

{- | A frozen class: no lend state, methods receive the payload by value, and
any number of threads may read it at once.
The payload must be 'Movable', since it is moved into GC ownership.
-}
class (Movable a) => PyFrozenClass a where
  pyFrozenClassName :: Proxy a -> Text
  pyFrozenClassDoc :: Proxy a -> Text
  pyFrozenClassDoc _ = ""
  pyFrozenClassTypeCell :: Proxy a -> TypeCell

  -- | The witness that the instance is trusted; see Note [Sealed classes] in "H2Py.Object.Internal".
  pyFrozenClassSealed :: Proxy a -> Sealed

{- | A Haskell class extending another Haskell class: @pyclassWith (... & extends ''Parent) ''Child@.
The child's type has the parent's in its bases, PEP 697 appends the child's
cell to the parent's layout, and each level keeps its own payload and word.
The instance is generated by @pyclass@; one level of extension is supported.
-}
class (PyClass c, PyClass p) => PyExtends c p | c -> p where
  -- | The witness that the extension is real; see Note [Sealed classes] in "H2Py.Object.Internal".
  pyExtendsSealed :: Proxy c -> Proxy p -> Sealed

-- | The type object of a class, attached; fails with @RuntimeError@ before module initialisation.
classType :: forall a. (PyClass a) => IO (Either PyErr (Ptr PyTypeObject))
classType = case pyClassSealed (Proxy @a) of
  UnsafeSealed -> do
    p <- readTypeCell (pyClassTypeCell (Proxy @a))
    pure
      if p == nullPtr
        then Left (runtimeError ("H2Py: the class " <> pyClassName (Proxy @a) <> " has not been registered by a module"))
        else Right (castPtr p)

{- | The type object of a class for a @PyTypeOf@ instance; throws
'ClassNotRegistered' before the module is initialised, so that no @NULL@ ever
reaches @PyObject_IsInstance@.
-}
requireTypeCell :: Text -> TypeCell -> IO (Ptr PyObject)
requireTypeCell name cell = do
  p <- readTypeCell cell
  NonLinear.when (p == nullPtr) (throwIO (ClassNotRegistered name))
  pure p

-- | The result codes of the shim's claims.
data ClaimResult = ClaimOk | ClaimBusy | ClaimExported | ClaimPoisoned
  deriving stock (Show, Eq)

claimResult :: CInt -> ClaimResult
claimResult 0 = ClaimOk
claimResult 1 = ClaimBusy
claimResult 2 = ClaimExported
claimResult _ = ClaimPoisoned

claimError :: Text -> ClaimResult -> PyErr
claimError name = \case
  ClaimOk -> systemError "H2Py: claimError on a successful claim"
  ClaimBusy -> runtimeError ("busy: " <> name <> " is already borrowed by another scope")
  ClaimExported -> bufferError (name <> " has live buffer exports and cannot be borrowed")
  ClaimPoisoned -> runtimeError (name <> ": object poisoned by an interrupted update")

{- | The payload of an object whose class is @a@, through the stable pointer in
its cell.
Trusted: the caller holds a claim on the word, or is the deallocator.
-}
readPayload :: forall a. Ptr PyObject -> Ptr PyTypeObject -> IO a
readPayload obj ty = do
  cell <- c_cellOf obj ty
  sp <- c_cellPayload cell
  deRefStablePtr (castPtrToStablePtr sp :: StablePtr a)

{- | Allocate an instance through the type being constructed when a
constructor is running for a subclass (the @subclassable@ option), else
through the class's own type.
-}
allocateInstance :: Ptr Arena -> Ptr PyTypeObject -> IO (PyResult (Ptr PyObject))
allocateInstance arena ownType = do
  ctor <- c_arenaTakeCtorType arena ownType
  ty <-
    if ctor == nullPtr
      then pure ownType
      else do
        sub <- c_typeIsSubtype ctor ownType
        pure (if sub /= 0 then ctor else ownType)
  obj <- c_allocInstance ty
  if obj == nullPtr then Left <$> takeError else pure (Right obj)

-- | Move a payload into the cell that the given type owns in the object.
installPayload :: forall a. Ptr PyObject -> Ptr PyTypeObject -> a -> IO ()
installPayload obj ty payload = do
  sp <- newStablePtr payload
  cell <- c_cellOf obj ty
  c_cellSetPayload cell (castStablePtrToPtr sp)

-- | Allocate an instance of the class and move the payload into it.
newObject :: forall a π γ. (PyClass a) => a %1 -> Py π γ (PyResult (Bound π a))
newObject = Unsafe.toLinear \payload -> unsafePyArena \arena -> do
  ety <- classType @a
  case ety of
    Left e -> evaluate (consume payload) >> pure (Left e)
    Right ownType -> do
      r <- allocateInstance arena ownType
      case r of
        Left e -> evaluate (consume payload) >> pure (Left e)
        Right obj -> do
          installPayload obj ownType payload
          c_arenaRegister arena obj
          pure (Right (unsafeBoundFromPtr obj))

{- | Allocate an instance of a class that extends another Haskell class, moving
the parent's payload and the child's into their own cells.
-}
newObjectWith :: forall c p π γ. (PyExtends c p) => p %1 -> c %1 -> Py π γ (PyResult (Bound π c))
newObjectWith = Unsafe.toLinear2 \parent child -> unsafePyArena \arena -> do
  ec <- classType @c
  ep <- classType @p
  case (ec, ep) of
    (Left e, _) -> evaluate (consume parent) >> evaluate (consume child) >> pure (Left e)
    (_, Left e) -> evaluate (consume parent) >> evaluate (consume child) >> pure (Left e)
    (Right childType, Right parentType) -> do
      r <- allocateInstance arena childType
      case r of
        Left e -> evaluate (consume parent) >> evaluate (consume child) >> pure (Left e)
        Right obj -> do
          installPayload obj parentType parent
          installPayload obj childType child
          c_arenaRegister arena obj
          pure (Right (unsafeBoundFromPtr obj))

-- | The parent's view of a child: free, a retag along the declared extension.
super :: forall p c π. (PyExtends c p) => Borrowed π c -> Borrowed π p
{-# INLINE super #-}
super v = case pyExtendsSealed (Proxy @c) (Proxy @p) of
  UnsafeSealed -> unsafeRetagShare v

-- | The handle form of 'super', provided separately because 'Mut' is invariant in its payload.
superMut :: forall p c π. (PyExtends c p) => Bound π c %1 -> Bound π p
{-# INLINE superMut #-}
superMut b = case pyExtendsSealed (Proxy @c) (Proxy @p) of
  UnsafeSealed -> unsafeRetagMut b

{- | Claim the object for this scope and borrow its payload in place, for the
rest of the scope.
'Left' is @busy@, a live buffer export, or a poisoned object.
-}
derefMut :: forall a π π' γ. (PyClass a, π >= γ) => Bound π a %1 -> Py π' γ (PyResult (Mut γ a))
derefMut = Unsafe.toLinear \b -> case mutPtr b of
  (p, _) -> unsafePyArena \arena -> do
    ety <- classType @a
    case ety of
      Left e -> pure (Left e)
      Right ty -> do
        rc <- claimResult <$> c_cellClaimMut arena p ty
        case rc of
          ClaimOk -> Right . UnsafeAlias <$> readPayload @a p ty
          other -> pure (Left (claimError (pyClassName (Proxy @a)) other))

{- | Claim the object shared and borrow its payload in place; repeatable within
the scope and across scopes.
-}
derefShare :: forall a π π' γ. (PyClass a, π >= γ) => Borrowed π a -> Py π' γ (PyResult (Ur (Share γ a)))
derefShare ref = unsafePyArena \arena -> do
  ety <- classType @a
  case ety of
    Left e -> pure (Left e)
    Right ty -> do
      let p = refPtr ref
      rc <- claimResult <$> c_cellClaimShared arena p ty
      case rc of
        ClaimOk -> Right . Ur . UnsafeAlias <$> readPayload @a p ty
        other -> pure (Left (claimError (pyClassName (Proxy @a)) other))

{- | Claim shared, copy the payload, and release at once: a fresh owner.
A claim is released only by whoever installed it, so a reused hold of an
enclosing scope is left untouched.
-}
copyPayload :: forall a π π' γ. (PyClass a, Copyable a, π >= γ) => Borrowed π a -> Py π' γ (PyResult a)
copyPayload ref = unsafePyIO do
  ety <- classType @a
  case ety of
    Left e -> pure (Left e)
    Right ty -> do
      let p = refPtr ref
      cell <- c_cellOf p ty
      -- The transient shared claim is not recorded in the arena, so it is
      -- released here on every path, under mask against an asynchronous
      -- exception between the claim and the release.
      mask \restore -> do
        rc <- claimResult <$> c_cellCopyBegin cell
        case rc of
          ClaimOk -> do
            payload <- readPayload @a p ty
            r <- try (restore (evaluate (copy (UnsafeAlias payload :: Share γ a)))) `finally` c_cellCopyEnd cell
            case r of
              Left (e :: SomeException) -> pure (Left (runtimeError (T.pack ("H2Py: copyPayload failed: " <> show e))))
              Right a -> pure (Right a)
          other -> pure (Left (claimError (pyClassName (Proxy @a)) other))

{- | Read a frozen payload by value.
Trusted per instance: the object is an instance of the class.
-}
readFrozen :: forall a π π' γ. (PyFrozenClass a, π >= γ) => Borrowed π a -> Py π' γ (PyResult a)
readFrozen ref = case pyFrozenClassSealed (Proxy @a) of
  UnsafeSealed -> unsafePyIO do
    p <- readTypeCell (pyFrozenClassTypeCell (Proxy @a))
    if p == nullPtr
      then pure (Left (runtimeError ("H2Py: the class " <> pyFrozenClassName (Proxy @a) <> " has not been registered by a module")))
      else Right <$> readPayload @a (refPtr ref) (castPtr p)

-- | Allocate an instance of a frozen class, moving the payload into GC ownership.
newFrozenObject :: forall a π γ. (PyFrozenClass a) => a %1 -> Py π γ (PyResult (Bound π a))
newFrozenObject payload = case pyFrozenClassSealed (Proxy @a) of
  UnsafeSealed -> case move payload of
    Ur value -> unsafePyArena \arena -> do
      tp <- readTypeCell (pyFrozenClassTypeCell (Proxy @a))
      if tp == nullPtr
        then pure (Left (runtimeError ("H2Py: the class " <> pyFrozenClassName (Proxy @a) <> " has not been registered by a module")))
        else do
          let ty = castPtr tp
          r <- allocateInstance arena ty
          case r of
            Left e -> pure (Left e)
            Right obj -> do
              installPayload obj ty value
              c_arenaRegister arena obj
              pure (Right (unsafeBoundFromPtr obj))

-- * Receivers

-- | The receiver kind of a class whose payload is dereferenced shared: 'PyClass'.
data Lent

-- | The receiver kind of a frozen class, whose payload is read by value: 'PyFrozenClass'.
data Frozen

{- | What a slot or a receiver-form method is given for the object it is called
on, at the call's attachment @π@: the payload dereferenced shared for a class
with a lend word, the payload by value for a frozen class.
-}
type family Receiver k a (π :: Lifetime) :: Type where
  Receiver Lent a π = Share π a
  Receiver Frozen a π = a

{- | The receiver kind of a class, 'Lent' or 'Frozen', with what a registration
needs to know about it.
Mutable receivers are always @'Mut' π a@ and need 'PyClass'.
Instances are generated by @pyclass@ next to 'PyClass' or 'PyFrozenClass'.
-}
class PyReceiver a k | a -> k where
  -- | The Python name of the class.
  receiverName :: Proxy a -> Text

  -- | The docstring.
  receiverDoc :: Proxy a -> Text

  -- | The cell holding the type object.
  receiverTypeCell :: Proxy a -> TypeCell

  -- | Run a body on the receiver of a lent object.
  withReceiver :: forall π r. Proxy π -> Ptr PyObject -> (Receiver k a π -> Py π π (PyResult r)) -> Py π π (PyResult r)

  -- | The deallocator, given the class's type and the action that finishes the deallocation.
  receiverDealloc :: Proxy a -> Ptr PyTypeObject -> (Ptr PyObject -> IO ()) -> Ptr PyObject -> IO ()

-- | 'withReceiver' for a class with a lend word: dereference the object shared and continue.
withSharedPayload :: forall a π r. (PyClass a) => Proxy π -> Ptr PyObject -> (Share π a -> Py π π (PyResult r)) -> Py π π (PyResult r)
withSharedPayload _ self k = case share (unsafeBoundFromPtr self :: Bound π a) of
  Ur v -> Control.do
    r <- derefShare v
    continueShared r k

continueShared :: forall a π r. PyResult (Ur (Share π a)) %1 -> (Share π a -> Py π π (PyResult r)) -> Py π π (PyResult r)
continueShared (Left e) _ = Control.pure (Left e)
continueShared (Right (Ur s)) k = k s

-- | 'withReceiver' for a frozen class: read the payload by value and continue.
withFrozenPayload :: forall a π r. (PyFrozenClass a) => Proxy π -> Ptr PyObject -> (a -> Py π π (PyResult r)) -> Py π π (PyResult r)
withFrozenPayload _ self k = Control.do
  r <- readFrozen (unsafeBorrowedFromPtr self :: Borrowed π a)
  continueFrozen r k

continueFrozen :: forall a π r. (Movable a) => PyResult a %1 -> (a -> Py π π (PyResult r)) -> Py π π (PyResult r)
continueFrozen (Left e) _ = Control.pure (Left e)
continueFrozen (Right v) k = case move v of
  Ur x -> k x

-- * Deallocation

{- | The @tp_dealloc@ of a class with a payload: free the stable pointer, run
'consume' on the payload unless the word is poisoned, in which case the payload
is leaked rather than traversed, then finish: through the actual type's
@tp_free@ for a base class, or through the parent's @tp_dealloc@ for a class
that extends another.
Every exception is caught and reported with @PyErr_WriteUnraisable@, because an
exception escaping into the RTS's C entry point would terminate the process.
-}
deallocPayload :: forall a. (Consumable a) => Ptr PyTypeObject -> (Ptr PyObject -> IO ()) -> Ptr PyObject -> IO ()
deallocPayload ty finish self = do
  r <- try do
    cell <- c_cellOf self ty
    sp <- c_cellPayload cell
    NonLinear.unless (sp == nullPtr) do
      lend <- c_cellLend cell
      let stable = castPtrToStablePtr sp :: StablePtr a
      NonLinear.unless (lend == -2) do
        payload <- deRefStablePtr stable
        evaluate (consumeUnrestricted payload)
      freeStablePtr stable
      c_cellSetPayload cell nullPtr
  case r of
    Left (e :: SomeException) -> reportUnraisable self e
    Right () -> pure ()
  finish self

{- | Report a Haskell exception from a deallocator through Python's unraisable
hook, saving and restoring whatever exception the caller had pending.
-}
reportUnraisable :: Ptr PyObject -> SomeException -> IO ()
reportUnraisable self e = do
  pending <- c_takeError
  raiseErr (someExceptionToPyErr e)
  c_writeUnraisable self
  NonLinear.unless (pending == nullPtr) (c_setRaisedException pending)

-- | The @tp_dealloc@ of a frozen class: only the stable pointer goes.
deallocFrozen :: Ptr PyTypeObject -> (Ptr PyObject -> IO ()) -> Ptr PyObject -> IO ()
deallocFrozen ty finish self = do
  r <- try do
    cell <- c_cellOf self ty
    sp <- c_cellPayload cell
    NonLinear.unless (sp == nullPtr) do
      freeStablePtr (castPtrToStablePtr sp :: StablePtr ())
      c_cellSetPayload cell nullPtr
  case r of
    Left (e :: SomeException) -> reportUnraisable self e
    Right () -> pure ()
  finish self

-- | Consume a payload that reached us unrestricted, through the stable pointer.
consumeUnrestricted :: (Consumable a) => a -> ()
consumeUnrestricted a = consume a
