{-# LANGUAGE OverloadedStrings #-}

{- |
The stub renderer of section 5.11: every 'TypeHint' constructor, a
hand-built 'ModuleDesc' against a golden string, and 'checkStubs' against a
golden file.
No interpreter is involved: the description is a plain value.
-}
module H2Py.StubSpec (
  module H2Py.StubSpec,
) where

import Data.Text (Text)
import Data.Text qualified as T
import H2Py.Convert (TypeHint (..), renderHint)
import H2Py.Module
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit (assertBool, testCase, (@?=))

test_renderHint :: TestTree
test_renderHint =
  testGroup
    "renderHint"
    [ testCase "TName" (renderHint (TName "Counter") @?= "Counter")
    , testCase "TApply" (renderHint (TApply "dict" [TName "str", TName "float"]) @?= "dict[str, float]")
    , testCase "TApply, nested" (renderHint (TApply "list" [TApply "list" [TName "int"]]) @?= "list[list[int]]")
    , testCase "TUnion" (renderHint (TUnion [TName "int", TName "str"]) @?= "int | str")
    , testCase "TUnion of nothing is Any" (renderHint (TUnion []) @?= "Any")
    , testCase "TOptional" (renderHint (TOptional (TName "int")) @?= "int | None")
    , testCase "TOptional of a union" (renderHint (TOptional (TUnion [TName "int", TName "str"])) @?= "int | str | None")
    , testCase "TTuple" (renderHint (TTuple [TName "int", TName "str", TName "float"]) @?= "tuple[int, str, float]")
    , testCase "TTuple of nothing" (renderHint (TTuple []) @?= "tuple[()]")
    , testCase "TNone" (renderHint TNone @?= "None")
    , testCase "TAny" (renderHint TAny @?= "Any")
    ]

-- | A description built by hand, covering every shape the renderer distinguishes.
stubCase :: ModuleDesc
stubCase =
  ModuleDesc
    { moduleDescName = "stubcase"
    , moduleDescDoc = "A module description built by hand."
    , moduleDescFunctions =
        [ FunctionDesc "add" [ParamDesc (Just "x") (TName "int"), ParamDesc (Just "y") (TName "int")] (TName "int") "Add two integers." False False
        , FunctionDesc "first" [ParamDesc Nothing (TApply "list" [TName "int"])] (TOptional (TName "int")) "" False False
        , FunctionDesc "mixed" [ParamDesc Nothing TAny, ParamDesc (Just "flag") (TName "bool")] (TUnion [TName "int", TName "str"]) "" False False
        , FunctionDesc "nothing" [] TNone "Returns None." False False
        ]
    , moduleDescClasses =
        [ ClassDesc
            { classDescName = "Counter"
            , classDescDoc = "A counter."
            , classDescBases = []
            , classDescMethods =
                [ FunctionDesc "__init__" [ParamDesc (Just "n") (TName "int")] TNone "" True True
                , FunctionDesc "incr" [ParamDesc (Just "k") (TName "int")] TNone "Add k." True False
                , FunctionDesc "get" [] (TName "int") "" True False
                , FunctionDesc "pair" [ParamDesc Nothing (TName "int")] (TTuple [TName "int", TName "str"]) "" True False
                ]
            , classDescSlots = [FunctionDesc "__repr__" [] (TName "str") "" True False]
            }
        , ClassDesc "Empty" "" [] [] []
        , ClassDesc "Documented" "Only a docstring." [] [] []
        , ClassDesc "Seq" "" ["collections.abc.Sequence"] [] [FunctionDesc "__len__" [] (TName "int") "" True False]
        ]
    , moduleDescExceptions = [ExceptionDesc "OpsError" "ValueError"]
    , moduleDescSubmodules = [ModuleDesc "inner" "" [] [] [] []]
    }

-- | The rendering of 'stubCase', derived by hand from the renderer's rules.
stubCaseGolden :: Text
stubCaseGolden =
  T.unlines
    [ "# stubcase.pyi, generated by H2Py; do not edit."
    , "from typing import Any, Iterator"
    , "import collections.abc"
    , ""
    , "def add(x: int, y: int) -> int:"
    , "    \"\"\"Add two integers.\"\"\""
    , ""
    , "def first(arg0: list[int], /) -> int | None:"
    , "    ..."
    , ""
    , "def mixed(arg0: Any, flag: bool) -> int | str:"
    , "    ..."
    , ""
    , "def nothing() -> None:"
    , "    \"\"\"Returns None.\"\"\""
    , ""
    , "class Counter:"
    , "    \"\"\"A counter.\"\"\""
    , "    def __init__(self, n: int) -> None: ..."
    , "    def incr(self, k: int) -> None:"
    , "        \"\"\"Add k.\"\"\""
    , "    def get(self) -> int:"
    , "        ..."
    , "    def pair(self, arg0: int, /) -> tuple[int, str]:"
    , "        ..."
    , "    def __repr__(self) -> str:"
    , "        ..."
    , ""
    , "class Empty:"
    , "    ..."
    , ""
    , "class Documented:"
    , "    \"\"\"Only a docstring.\"\"\""
    , ""
    , "class Seq(collections.abc.Sequence[Any]):"
    , "    def __len__(self) -> int:"
    , "        ..."
    , ""
    , "class OpsError(ValueError): ..."
    , ""
    , ""
    , "# submodule stubcase.inner: see inner.pyi"
    , ""
    ]

test_renderStubs :: TestTree
test_renderStubs =
  testGroup
    "renderStubs"
    [ testCase "a hand-built description renders to the golden text" (renderStubs stubCase @?= stubCaseGolden)
    , testCase "an empty module renders the header alone" do
        renderStubs (ModuleDesc "empty" "" [] [] [] []) @?= "# empty.pyi, generated by H2Py; do not edit.\nfrom typing import Any, Iterator\n\n"
    ]

test_checkStubs :: TestTree
test_checkStubs =
  testGroup
    "checkStubs"
    [ testCase "the committed golden file is current" do
        ok <- checkStubs stubCase "test/golden/stubcase.pyi"
        assertBool "test/golden/stubcase.pyi differs from renderStubs stubCase" ok
    , testCase "a changed description no longer matches" do
        ok <- checkStubs stubCase {moduleDescFunctions = []} "test/golden/stubcase.pyi"
        assertBool "a stale golden file was accepted" (not ok)
    ]
