# stubcase.pyi, generated by H2Py; do not edit.
from typing import Any, Iterator
import collections.abc

def add(x: int, y: int) -> int:
    """Add two integers."""

def first(arg0: list[int], /) -> int | None:
    ...

def mixed(arg0: Any, flag: bool) -> int | str:
    ...

def nothing() -> None:
    """Returns None."""

class Counter:
    """A counter."""
    def __init__(self, n: int) -> None: ...
    def incr(self, k: int) -> None:
        """Add k."""
    def get(self) -> int:
        ...
    def pair(self, arg0: int, /) -> tuple[int, str]:
        ...
    def __repr__(self) -> str:
        ...

class Empty:
    ...

class Documented:
    """Only a docstring."""

class Seq(collections.abc.Sequence[Any]):
    def __len__(self) -> int:
        ...

class OpsError(ValueError): ...


# submodule stubcase.inner: see inner.pyi

