#!/usr/bin/env bash
# Write cabal.project.local with the include directory of the target CPython.
#
# H2Py's C shim and every extension module built with it include <Python.h>,
# and the include directory is taken from `sysconfig` of the interpreter the
# module is built for (pkg-config is not available in uv, pyenv or plain venvs).
# Usage: scripts/configure-python.sh [python-executable] [extra cabal.project.local lines...]
set -euo pipefail

root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
default_python="${root}/.venv/bin/python"
python="${1:-${H2PY_PYTHON:-${default_python}}}"
if [ ! -x "${python}" ] && ! command -v "${python}" >/dev/null 2>&1; then
  echo "configure-python: no interpreter at ${python}; create the venv (uv venv --python python3.13 .venv) or pass one" >&2
  exit 1
fi
if [ $# -gt 0 ]; then shift; fi

include="$("$python" -c 'import sysconfig; print(sysconfig.get_paths()["include"])')"
compiler="${H2PY_GHC:-ghc-9.12.4}"

{
  echo "-- Generated by scripts/configure-python.sh for ${python}; do not commit."
  echo "with-compiler: ${compiler}"
  echo "documentation: False"
  echo
  echo "package h2py"
  echo "  extra-include-dirs: ${include}"
  echo
  echo "package h2py-examples"
  echo "  extra-include-dirs: ${include}"
  for line in "$@"; do
    echo "$line"
  done
} > "${root}/cabal.project.local"

echo "wrote ${root}/cabal.project.local (Python.h from ${include}, compiler ${compiler})"
