#!/usr/bin/env bash
# Write cabal.project.local with the include directory of the target CPython.
#
# H2Py's C shim and every extension module built with it include <Python.h>,
# and the include directory is taken from `sysconfig` of the interpreter the
# module is built for (pkg-config is not available in uv, pyenv or plain venvs).
# It is written for h2py and for each package in H2PY_CABAL_PACKAGES, the
# packages whose C files include <h2py/init.h>.
# Usage: scripts/configure-python.sh [python-executable] [extra cabal.project.local lines...]
# Environment:
#   H2PY_PYTHON          the interpreter when none is passed (default: .venv/bin/python)
#   H2PY_GHC             the compiler (default: ghc-9.12.4)
#   H2PY_CABAL_PACKAGES  the extension packages, space-separated (default: h2py-examples)
set -euo pipefail

root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
default_python="${root}/.venv/bin/python"
python="${1:-${H2PY_PYTHON:-${default_python}}}"
if [ ! -x "${python}" ] && ! command -v "${python}" >/dev/null 2>&1; then
  echo "configure-python: no interpreter at ${python}; create the venv (uv venv --python python3.13 .venv) or pass one" >&2
  exit 1
fi
if [ $# -gt 0 ]; then shift; fi

include="$("$python" -c 'import sysconfig; print(sysconfig.get_paths()["include"])')"
compiler="${H2PY_GHC:-ghc-9.12.4}"
packages=(h2py)
for package in ${H2PY_CABAL_PACKAGES:-h2py-examples}; do
  case " ${packages[*]} " in
    *" ${package} "*) ;;
    *) packages+=("${package}") ;;
  esac
done

{
  echo "-- Generated by scripts/configure-python.sh for ${python}; do not commit."
  echo "with-compiler: ${compiler}"
  echo "documentation: False"
  for package in "${packages[@]}"; do
    echo
    echo "package ${package}"
    echo "  extra-include-dirs: ${include}"
  done
  for line in "$@"; do
    echo "$line"
  done
} > "${root}/cabal.project.local"

echo "wrote ${root}/cabal.project.local (Python.h from ${include} for ${packages[*]}, compiler ${compiler})"
