#!/usr/bin/env bash
# Regenerate h2py/include/h2py/weakapi.h: a `#pragma weak` for every CPython
# symbol the h2py library references, taken from the undefined symbols of its
# built shared library, so that every reference from the shim is weak and GHC
# can load the library without an interpreter to run Template Haskell.
# dyld binds every symbol at load time on macOS; on Linux, GHC's loader binds
# lazily only calls through the PLT, and a function whose address the shim
# takes (a slot table entry) needs its symbol at load time as well.
#
# Usage: scripts/gen-weakapi.sh          rewrite the header
#        scripts/gen-weakapi.sh --check  fail if a referenced symbol is missing
set -euo pipefail
root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
out="${root}/h2py/include/h2py/weakapi.h"
case "$(uname -s)" in
  Darwin) ext=dylib ;;
  *) ext=so ;;
esac
lib="$(find "${root}/dist-newstyle" -name "libHSh2py-*.${ext}" -type f | head -1)"
if [ -z "${lib}" ]; then
  echo "gen-weakapi: the h2py library has not been built yet" >&2
  exit 1
fi
# Mach-O names carry a leading underscore; ELF names do not.  GNU nm prints
# the symbol type before the name, macOS nm only the name.
case "$(uname -s)" in
  Darwin) strip='s/^_//' ;;
  *) strip='' ;;
esac
symbols="$(nm -u "${lib}" | awk '{print $NF}' | sed -e "${strip}" | grep -E '^(Py|_Py)[A-Za-z0-9_]*$' | sort -u || true)"
if [ "${1:-}" = "--check" ]; then
  if [ -z "${symbols}" ]; then
    echo "gen-weakapi: ${lib} references no CPython function; is it the built h2py library?" >&2
    exit 1
  fi
  missing=0
  while IFS= read -r sym; do
    [ -n "${sym}" ] || continue
    if ! grep -q "^#pragma weak ${sym}\$" "${out}"; then
      echo "weakapi.h lacks ${sym}" >&2
      missing=1
    fi
  done <<< "${symbols}"
  if [ "${missing}" -ne 0 ]; then
    echo "run scripts/gen-weakapi.sh" >&2
    exit 1
  fi
  # Every CPython reference must have been merged as weak, or GHC cannot
  # load the library for Template Haskell.  A strong one means a C file was
  # compiled without <h2py/weakapi.h> or a Haskell foreign import bypasses
  # cbits/api.c.
  if [ "$(uname -s)" = Darwin ]; then
    strong="$(nm -m "${lib}" | grep -E '^ +\(undefined\) external _(Py|_Py)' || true)"
  else
    strong="$(nm -D --undefined-only "${lib}" | awk '$1 == "U" && $2 ~ /^_?Py/' || true)"
  fi
  if [ -n "${strong}" ]; then
    echo "strong CPython references remain in ${lib}:" >&2
    echo "${strong}" >&2
    exit 1
  fi
  echo "weakapi.h covers every CPython reference, and every reference is weak"
  exit 0
fi
existing=""
if [ -f "${out}" ]; then
  existing="$(grep -E '^#pragma weak ' "${out}" | sed -e 's/^#pragma weak //')"
fi
all="$(printf '%s\n%s\n' "${existing}" "${symbols}" | grep -v '^$' | sort -u)"
{
  echo "/* Generated by scripts/gen-weakapi.sh; do not edit by hand."
  echo " *"
  echo " * Every CPython symbol the h2py library references, marked as a weak"
  echo " * reference: the library must be loadable by GHC, with no interpreter in"
  echo " * the process, to run Template Haskell splices, and the references bind"
  echo " * to the interpreter as usual once an extension module is imported."
  echo " * dyld binds every symbol at load time on macOS, and on Linux a function"
  echo " * whose address the shim takes needs its symbol at load time too."
  echo " * Included by <h2py/h2py.h> after <Python.h>; a pragma for a symbol that"
  echo " * is not referenced is harmless, so the list only grows. */"
  echo "#ifndef H2PY_WEAKAPI_H"
  echo "#define H2PY_WEAKAPI_H"
  while IFS= read -r sym; do
    [ -n "${sym}" ] || continue
    echo "#pragma weak ${sym}"
  done <<< "${all}"
  echo ""
  echo "#ifdef H2PY_WEAKAPI_TABLE"
  echo "/* Every symbol above with its address, which is NULL when the interpreter"
  echo " * lacks it; h2py.c defines H2PY_WEAKAPI_TABLE and checks the table when"
  echo " * a module is imported (h2py_check_cpython_symbols). */"
  echo "static const struct {"
  echo "    const char *name;"
  echo "    const void *address;"
  echo "} h2py_weakapi_table[] = {"
  while IFS= read -r sym; do
    [ -n "${sym}" ] || continue
    echo "    {\"${sym}\", (const void *) &${sym}},"
  done <<< "${all}"
  echo "};"
  echo "#endif /* H2PY_WEAKAPI_TABLE */"
  echo "#endif /* H2PY_WEAKAPI_H */"
} > "${out}"
echo "wrote ${out} ($(printf '%s\n' "${all}" | grep -c .) symbols)"
