#!/usr/bin/env bash
# Regenerate h2py/include/h2py/weakapi.h: a `#pragma weak` for every CPython
# symbol the h2py library references, taken from the undefined symbols of its
# built dylib, so that every reference from the shim is weak on macOS and GHC
# can dlopen the library without an interpreter to run Template Haskell.
#
# Usage: scripts/gen-weakapi.sh          rewrite the header
#        scripts/gen-weakapi.sh --check  fail if a referenced symbol is missing
set -euo pipefail
root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
out="${root}/h2py/include/h2py/weakapi.h"
case "$(uname -s)" in
  Darwin) ext=dylib ;;
  *) ext=so ;;
esac
lib="$(find "${root}/dist-newstyle" -name "libHSh2py-*.${ext}" -type f | head -1)"
if [ -z "${lib}" ]; then
  echo "gen-weakapi: the h2py library has not been built yet" >&2
  exit 1
fi
symbols="$(nm -u "${lib}" | sed -e 's/^_//' | grep -E '^(Py|_Py)[A-Za-z0-9_]*$' | sort -u)"
if [ "${1:-}" = "--check" ]; then
  missing=0
  while IFS= read -r sym; do
    [ -n "${sym}" ] || continue
    if ! grep -q "^#pragma weak ${sym}\$" "${out}"; then
      echo "weakapi.h lacks ${sym}" >&2
      missing=1
    fi
  done <<< "${symbols}"
  if [ "${missing}" -ne 0 ]; then
    echo "run scripts/gen-weakapi.sh" >&2
    exit 1
  fi
  if [ "$(uname -s)" = Darwin ]; then
    # Every CPython reference must have been merged as weak, or GHC cannot
    # load the library for Template Haskell.  A strong one means a C file
    # was compiled without <h2py/weakapi.h> or a Haskell foreign import
    # bypasses cbits/api.c.
    strong="$(nm -m "${lib}" | grep -E '^ +\(undefined\) external _(Py|_Py)' || true)"
    if [ -n "${strong}" ]; then
      echo "strong CPython references remain in ${lib}:" >&2
      echo "${strong}" >&2
      exit 1
    fi
  fi
  echo "weakapi.h covers every CPython reference, and every reference is weak"
  exit 0
fi
existing=""
if [ -f "${out}" ]; then
  existing="$(grep -E '^#pragma weak ' "${out}" | sed -e 's/^#pragma weak //')"
fi
all="$(printf '%s\n%s\n' "${existing}" "${symbols}" | grep -v '^$' | sort -u)"
{
  echo "/* Generated by scripts/gen-weakapi.sh; do not edit by hand."
  echo " *"
  echo " * Every CPython symbol the h2py library references, marked as a weak"
  echo " * reference on macOS: the library must be loadable by GHC, with no"
  echo " * interpreter in the process, to run Template Haskell splices, and the"
  echo " * references bind to the interpreter as usual once an extension module is"
  echo " * imported.  Included by <h2py/h2py.h> after <Python.h>; a pragma for a"
  echo " * symbol that is not referenced is harmless, so the list only grows. */"
  echo "#ifndef H2PY_WEAKAPI_H"
  echo "#define H2PY_WEAKAPI_H"
  echo "#ifdef __APPLE__"
  while IFS= read -r sym; do
    [ -n "${sym}" ] || continue
    echo "#pragma weak ${sym}"
  done <<< "${all}"
  echo "#endif /* __APPLE__ */"
  echo "#endif /* H2PY_WEAKAPI_H */"
} > "${out}"
echo "wrote ${out} ($(printf '%s\n' "${all}" | grep -c .) symbols)"
