#!/usr/bin/env python3
"""Keep the licence files of an H2Py extension wheel complete.

A wheel of an H2Py extension module carries the GHC runtime and every Haskell
library the module links against, bundled by delocate (macOS) or auditwheel
(Linux), and each of them must travel with its licence.
The licence files live in a committed directory that the packaging lists in
``project.license-files``, because hatchling reads that field before any
build hook runs; this script writes that directory and checks it against the
build plan, the way ``h2py-stubs.py`` checks the committed stubs.

Usage::

    wheel-licenses.py --write --licenses DIR --pyproject FILE flib:h2py_examples
    wheel-licenses.py --check --licenses DIR --pyproject FILE flib:h2py_examples
    wheel-licenses.py --check-wheel WHEEL --licenses DIR --pyproject FILE flib:h2py_examples

DIR holds the third-party licences; the package's own licence is copied to
``LICENSE`` next to ``pyproject.toml``, which is where ``license-files``
expects it.

The component is the foreign library whose wheel is being built.
Its library dependencies are closed transitively over
``dist-newstyle/cache/plan.json``.
That closure is a superset of what the repair tools bundle (on macOS GHC
links with ``-dead_strip_dylibs``), and ``--check-wheel`` checks the repaired
wheel itself.
It finds every shared library in the wheel by its magic bytes, wherever it
lies: each Haskell one must belong to the closure, the GHC runtime must be
among them, and nothing else may be there but, on Linux, GMP and GHC's
libffi, at the versions the notices name (the SBOM auditwheel writes for GMP,
the version string inside each library otherwise).
Every licence file must be in the wheel byte for byte, and its metadata must
list them all and carry the licence expression of ``pyproject.toml``.
Components of other origin compiled into a library have notices of their own
(``EXTRA_NOTICES``), found by searching the GHC source and the store
packages' sources for third-party copyright notices.
For each package the licence text comes from the package directory for
local packages and from ``<store>/<ghc>/<unit>/share/doc`` for store packages.
The libraries that come with GHC need the GHC source tree of the same version
(``--ghc-source``, the unpacked ``ghc-<version>-src.tar.xz``), because a GHC
installation puts GHC's own licence in every boot library's documentation
directory, whatever the library's actual licence; the runtime system is
covered by GHC's licence.
Without ``--ghc-source``, the sections of boot libraries are taken as they
are: ``--write`` keeps them and ``--check`` only requires them to exist.

``--write`` merges the closure into ``HASKELL-LIBRARIES.txt`` under DIR,
keeping sections already there, so that running it on each platform leaves
the union of what every platform bundles; ``--prune`` drops the sections the
current closure does not need.
It also copies the package's own licence next to ``pyproject.toml`` and
prints the SPDX identifiers its licence expression must name.

``--check`` writes nothing and exits 1 when a package of the closure has no
section or a different licence text, when the copied licence differs from
the package's own, when a fixed file is missing or names another GHC, or when
the licence expression of ``pyproject.toml`` is not a plain conjunction naming
every identifier in use.
Sections are keyed by package name and version, so a new GHC or a new index
state that changes a version fails the check until ``--write`` has run.
"""

from __future__ import annotations

import argparse
import glob
import zipfile
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

HEADER = """\
Licences of the Haskell libraries bundled in this wheel
=======================================================

Generated by scripts/wheel-licenses.py from the build plan; do not edit.
The wheel carries the GHC runtime and the Haskell libraries the extension
module links against, each under the licence reproduced in its section.
"""

RULE = "-" * 72

# Files under the licence directory that are written by hand, not generated;
# README.txt says what each one covers.
FIXED_FILES = (
    "README.txt",
    "GMP-NOTICE.txt",
    "LGPL-3.0.txt",
    "GPL-3.0.txt",
    "LIBFFI-LICENSE.txt",
    "XXHASH-LICENSE.txt",
    "LLVM-LICENSE.txt",
)

# Code of other origin compiled into a package, whose notice the package's own
# licence does not carry: xxHash in the runtime (rts/Hash.c) and in hashable,
# LLVM's ELF relocation tables in the runtime's linker, GMP in ghc-bignum.
EXTRA_NOTICES = {
    "rts": ("XXHASH-LICENSE.txt", "LLVM-LICENSE.txt"),
    "hashable": ("XXHASH-LICENSE.txt",),
    "ghc-bignum": ("GMP-NOTICE.txt", "LGPL-3.0.txt", "GPL-3.0.txt"),
}

# Identifiers the licence texts add beyond the packages' declared licences:
# GMP, libffi, xxHash, LLVM's tables, and the Haskell Report's licence, which
# base, array and ghc-internal carry in their licence files.
FIXED_SPDX = {"LGPL-3.0-or-later", "MIT", "BSD-2-Clause", "NCSA", "HaskellReport"}

# Libraries other than Haskell ones that a repaired wheel may bundle, per
# platform: GMP and GHC's libffi on Linux, under auditwheel's names, nothing on
# macOS, where GMP is inside libHSghc-bignum and libffi is the system's.
BUNDLED_OTHERS = {
    "linux": (r"libgmp-[0-9a-f]{8}\.so\.10(\.[0-9.]+)?", r"libffi-[0-9a-f]{8}\.so\.8(\.[0-9.]+)?"),
    "macos": (),
}

BINARY_MAGIC = (b"\x7fELF", b"\xcf\xfa\xed\xfe", b"\xce\xfa\xed\xfe", b"\xca\xfe\xba\xbe", b"\xfe\xed\xfa\xcf")

LICENCE_GLOBS = ("LICEN[CS]E*", "COPYING*")


@dataclass(frozen=True)
class Package:
    name: str
    version: str
    spdx: str
    text: str | None

    @property
    def key(self) -> str:
        return f"{self.name}-{self.version}"


class LicenceError(Exception):
    pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="wheel-licenses",
        description="Write or check the licence files of an H2Py extension wheel.",
    )
    parser.add_argument("component", help="the foreign library, as in the build plan, e.g. flib:h2py_examples")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="merge the closure into the licence directory")
    mode.add_argument("--check", action="store_true", help="write nothing; exit 1 if anything is missing or stale")
    mode.add_argument(
        "--check-wheel",
        metavar="WHEEL",
        help="write nothing; exit 1 unless every library the repaired WHEEL bundles has its licence in it",
    )
    parser.add_argument("--licenses", required=True, metavar="DIR", help="the committed licence directory")
    parser.add_argument("--pyproject", required=True, metavar="FILE", help="the pyproject.toml of the wheel")
    parser.add_argument(
        "--plan",
        default="dist-newstyle/cache/plan.json",
        metavar="FILE",
        help="cabal's build plan (default: %(default)s)",
    )
    parser.add_argument("--prune", action="store_true", help="with --write, drop sections outside the closure")
    parser.add_argument(
        "--ghc-source",
        metavar="DIR",
        help="the unpacked source tree of the same GHC, for the licences of its boot libraries",
    )
    args = parser.parse_args(argv)

    try:
        plan = json.loads(Path(args.plan).read_text())
        root, closure = closure_of(plan, args.component)
        resolver = Resolver(plan, Path(args.ghc_source) if args.ghc_source else None)
        packages = sorted((resolver.package(unit) for unit in closure), key=lambda p: (p.name.lower(), p.version))
        own_licence = resolver.local_licence_text(root)
    except LicenceError as err:
        print(f"wheel-licenses: {err}", file=sys.stderr)
        return 2

    licences = Path(args.licenses)
    haskell_file = licences / "HASKELL-LIBRARIES.txt"
    own_file = Path(args.pyproject).parent / "LICENSE"
    existing = parse_sections(haskell_file.read_text()) if haskell_file.exists() else {}
    spdx = spdx_ids(p.spdx for p in packages) | spdx_ids([resolver.local_spdx(root)]) | FIXED_SPDX

    if args.check_wheel:
        return check_wheel(
            Path(args.check_wheel),
            closure,
            licences,
            own_file,
            read_expression(Path(args.pyproject)),
            args.component.split(":", 1)[1],
        )

    if args.write:
        sections = {} if args.prune else dict(existing)
        unknown = []
        for p in packages:
            if p.text is not None:
                sections[p.key] = (p.spdx, p.text)
            elif p.key in existing:
                sections[p.key] = existing[p.key]
            else:
                unknown.append(p.key)
        if unknown:
            print(
                f"wheel-licenses: {', '.join(unknown)} came with GHC and need --ghc-source for their licences",
                file=sys.stderr,
            )
            return 1
        added = sorted(set(sections) - set(existing))
        licences.mkdir(parents=True, exist_ok=True)
        haskell_file.write_text(render_sections(sections))
        if added:
            print(
                "wheel-licenses: new sections: "
                + ", ".join(added)
                + "; read their C, C++ and assembly sources for code of other origin, whose notice"
                " their own licence may not carry, and list it in EXTRA_NOTICES"
            )
        shutil.copyfile(resolver.local_licence_files(root)[0], own_file)
        print(f"wrote {haskell_file} ({len(sections)} packages) and {own_file}")
        missing_fixed = [f for f in FIXED_FILES if not (licences / f).is_file()]
        if missing_fixed:
            print(f"wheel-licenses: {licences} lacks {', '.join(missing_fixed)}", file=sys.stderr)
        print("SPDX identifiers the licence expression must name: " + " ".join(sorted(spdx)))
        return 0

    problems: list[str] = []
    for p in packages:
        if p.key not in existing:
            problems.append(f"no section for {p.key} ({p.spdx})")
        elif p.text is not None and normalise(existing[p.key][1]) != normalise(p.text):
            problems.append(f"the section for {p.key} differs from its installed licence")
    if not own_file.is_file() or normalise(own_file.read_text()) != normalise(own_licence):
        problems.append(f"{own_file} differs from the licence of {root['pkg-name']}")
    for f in FIXED_FILES:
        if not (licences / f).is_file():
            problems.append(f"{licences / f} is missing")
    for p in packages:
        for f in EXTRA_NOTICES.get(p.name, ()):
            if not (licences / f).is_file():
                problems.append(f"{p.key} needs {licences / f}, which is missing")
    gmp_notice = licences / "GMP-NOTICE.txt"
    ghc = plan["compiler-id"]
    if gmp_notice.is_file() and ghc not in gmp_notice.read_text():
        problems.append(f"{gmp_notice} does not name {ghc}, the compiler of the build plan")
    expression = read_expression(Path(args.pyproject))
    if not re.fullmatch(r"[A-Za-z0-9.+-]+( AND [A-Za-z0-9.+-]+)*", expression):
        problems.append(f"the licence expression of {args.pyproject} must be identifiers joined by AND")
    named = set(expression.split(" AND "))
    for ident in sorted(spdx - named):
        problems.append(f"the licence expression of {args.pyproject} does not name {ident}")
    if problems:
        for problem in problems:
            print(f"wheel-licenses: {problem}", file=sys.stderr)
        print(
            "wheel-licenses: run scripts/wheel-licenses.py --write with the same arguments, "
            "review the result, and update the licence expression",
            file=sys.stderr,
        )
        return 1
    print(f"wheel-licenses: {len(packages)} bundled packages covered by {licences}")
    return 0


def check_wheel(
    wheel: Path, closure: list[dict], licences: Path, own_file: Path, expression: str, module: str
) -> int:
    """Every library the repaired wheel bundles is covered, and the licences are in it."""
    unit_ids = {unit["id"] for unit in closure}
    platform = "macos" if "-macosx_" in wheel.name else "linux"
    problems: list[str] = []
    found_rts = False
    with zipfile.ZipFile(wheel) as archive:
        names = archive.namelist()
        binaries = []
        for name in names:
            if name.endswith("/") or re.fullmatch(re.escape(module) + r"\.abi3t?\.so", name):
                continue
            with archive.open(name) as f:
                if f.read(4) in BINARY_MAGIC:
                    binaries.append(name)
        for name in binaries:
            file = name.rsplit("/", 1)[-1]
            if file.startswith("libHS"):
                try:
                    unit = unit_of_library(file)
                except LicenceError as err:
                    problems.append(str(err))
                    continue
                found_rts = found_rts or unit.startswith("rts-")
                if unit not in unit_ids:
                    problems.append(f"{name} is bundled, but {unit} is not in the build plan's closure")
            elif not any(re.fullmatch(pattern, file) for pattern in BUNDLED_OTHERS[platform]):
                problems.append(f"{name} is bundled, and nothing here covers it on {platform}")
        if not found_rts:
            problems.append("the GHC runtime (libHSrts) is not among the bundled libraries")
        problems += check_versions(archive, names, binaries, licences, platform)
        dist_info = next((n.split("/", 1)[0] for n in names if n.endswith(".dist-info/METADATA")), None)
        if dist_info is None:
            problems.append("the wheel has no METADATA")
        else:
            metadata = archive.read(f"{dist_info}/METADATA").decode()
            listed = set(re.findall(r"^License-File: (.+)$", metadata, re.MULTILINE))
            got = re.findall(r"^License-Expression: (.+)$", metadata, re.MULTILINE)
            if got != [expression]:
                problems.append(f"the metadata's License-Expression is {got}, not {expression!r}")
            wanted = {"LICENSE": own_file} | {f"{licences.name}/{f.name}": f for f in licences.iterdir() if f.is_file()}
            for relative, source in sorted(wanted.items()):
                member = f"{dist_info}/licenses/{relative}"
                if relative not in listed:
                    problems.append(f"the metadata lists no License-File {relative}")
                if member not in names:
                    problems.append(f"the wheel does not carry the licence file {relative}")
                elif archive.read(member) != source.read_bytes():
                    problems.append(f"the wheel's {relative} differs from {source}")
    for problem in problems:
        print(f"wheel-licenses: {wheel.name}: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"wheel-licenses: {wheel.name}: {len(binaries)} bundled libraries, each covered by the licences it carries")
    return 0


def check_versions(archive, names: list[str], binaries: list[str], licences: Path, platform: str) -> list[str]:
    """GMP and libffi in the wheel are the versions the notices name."""
    problems: list[str] = []
    notice = (licences / "GMP-NOTICE.txt").read_text()
    readme = (licences / "README.txt").read_text()
    if platform == "macos":
        gmp = re.search(r"GMP (\d+\.\d+\.\d+) compiled into", notice)
        bignum = [b for b in binaries if b.rsplit("/", 1)[-1].startswith("libHSghc-bignum")]
        if not gmp or not bignum or not version_in(archive.read(bignum[0]), gmp.group(1)):
            problems.append("libHSghc-bignum does not contain the GMP version GMP-NOTICE.txt names")
        return problems
    gmp = re.search(r"gmp (\d[\w.]*-[\w.]+) package", notice)
    sboms = [n for n in names if re.search(r"\.dist-info/sboms/.+\.json$", n)]
    purls = [c.get("purl", "") for n in sboms for c in json.loads(archive.read(n)).get("components", [])]
    shipped = [p.split("@", 1)[1].split("?", 1)[0] for p in purls if "/gmp@" in p]
    if not gmp or shipped != [gmp.group(1)]:
        problems.append(f"the wheel's SBOM names gmp {shipped}, GMP-NOTICE.txt {gmp.group(1) if gmp else None}")
    ffi = re.search(r"libffi (\d+\.\d+\.\d+)", readme)
    libffi = [b for b in binaries if b.rsplit("/", 1)[-1].startswith("libffi-")]
    if not ffi or not libffi or not version_in(archive.read(libffi[0]), ffi.group(1)):
        problems.append("the bundled libffi does not contain the version README.txt names")
    return problems


def version_in(binary: bytes, version: str) -> bool:
    """The version appears in the library as a string of its own."""
    return re.search(rb"(?<![0-9.])" + re.escape(version.encode()) + rb"(?![0-9.])", binary) is not None


def unit_of_library(file: str) -> str:
    """The unit id of a bundled Haskell library, from its file name.

    GHC names a shared library ``libHS<unit id>[_<way>]-ghc<version>.<ext>``;
    auditwheel inserts ``-<8 hex digits>`` before the first dot of the name.
    """
    stem, dot, rest = file.partition(".")
    stem = re.sub(r"-[0-9a-f]{8}$", "", stem)
    name = stem + dot + rest
    m = re.match(r"^libHS(.+?)(?:_(?:thr|debug|thr_debug|p|l))?-ghc[0-9.]+\.(?:dylib|so)(?:\.[0-9.]+)?$", name)
    if not m:
        raise LicenceError(f"cannot read a unit id from {file}")
    return m.group(1)


def closure_of(plan: dict, component: str) -> tuple[dict, list[dict]]:
    """The unit of the component, and the library units it depends on transitively."""
    units = {u["id"]: u for u in plan["install-plan"]}
    roots = [u for u in units.values() if u.get("component-name") == component]
    roots += [u for u in units.values() if component in u.get("components", {})]
    if len(roots) != 1:
        raise LicenceError(f"{component} names {len(roots)} units in the build plan, not one")
    root = roots[0]
    seen: dict[str, dict] = {}
    pending = list(library_depends(root, component))
    while pending:
        unit_id = pending.pop()
        if unit_id in seen:
            continue
        if unit_id not in units:
            raise LicenceError(f"the build plan has no unit {unit_id}")
        unit = units[unit_id]
        seen[unit_id] = unit
        pending.extend(library_depends(unit, None))
    return root, list(seen.values())


def library_depends(unit: dict, component: str | None) -> list[str]:
    if "components" in unit:
        comps = unit["components"]
        names = [component] if component else [c for c in comps if c == "lib" or c.startswith("lib:")]
        return [d for c in names for d in comps.get(c, {}).get("depends", [])]
    return list(unit.get("depends", []))


class Resolver:
    """Finds the licence text and SPDX identifier of each unit where it is installed."""

    def __init__(self, plan: dict, ghc_source: Path | None) -> None:
        self.compiler = plan["compiler-id"]
        self.ghc_source = ghc_source
        self._libdir: Path | None = None

    def package(self, unit: dict) -> Package:
        name, version = unit["pkg-name"], unit["pkg-version"]
        if unit.get("style") == "local":
            return Package(name, version, self.local_spdx(unit), self.local_licence_text(unit))
        if unit["type"] == "pre-existing":
            conf = self.libdir() / "package.conf.d" / f"{unit['id']}.conf"
            return Package(name, version, conf_field(conf, "license"), self.boot_licence_text(name))
        unit_dir, conf = self.store_unit(unit["id"])
        files = licence_files(unit_dir / "share" / "doc")
        if not files:
            raise LicenceError(f"no licence file installed for {name}-{version} under {unit_dir / 'share' / 'doc'}")
        return Package(name, version, conf_field(conf, "license"), join_texts(files))

    # Local packages: the .cabal file names the licence.

    def local_spdx(self, unit: dict) -> str:
        return cabal_field(cabal_file(unit), "license") or "NONE"

    def local_licence_files(self, unit: dict) -> list[Path]:
        cabal = cabal_file(unit)
        names = (cabal_field(cabal, "license-file") or cabal_field(cabal, "license-files") or "").split()
        files = [cabal.parent / n.rstrip(",") for n in names]
        if not files or not all(f.is_file() for f in files):
            raise LicenceError(f"{cabal} names no licence file that exists")
        return files

    def local_licence_text(self, unit: dict) -> str:
        return join_texts(self.local_licence_files(unit))

    # Libraries that come with GHC.

    def libdir(self) -> Path:
        if self._libdir is None:
            ghc = os.environ.get("H2PY_GHC", self.compiler)
            try:
                out = subprocess.run([ghc, "--print-libdir"], capture_output=True, text=True, check=True)
            except (OSError, subprocess.CalledProcessError) as err:
                raise LicenceError(f"cannot run {ghc} --print-libdir: {err}") from err
            self._libdir = Path(out.stdout.strip())
        return self._libdir

    def boot_licence_text(self, name: str) -> str | None:
        """The licence of a boot library in the GHC source tree, or None without one."""
        if self.ghc_source is None:
            return None
        if name == "rts":
            files = licence_files(self.ghc_source)
        else:
            cabals = sorted(self.ghc_source.glob(f"libraries/**/{name}.cabal*"), key=lambda c: len(c.parts))
            files = licence_files(cabals[0].parent) if cabals else []
        if not files:
            raise LicenceError(f"no licence file for {name} in the GHC source tree at {self.ghc_source}")
        return join_texts(files)

    # Store packages.

    def stores(self, ask_cabal: bool) -> list[Path]:
        candidates: list[Path] = []
        for var in ("H2PY_CABAL_STORE",):
            if os.environ.get(var):
                candidates.append(Path(os.environ[var]))
        if os.environ.get("CABAL_DIR"):
            candidates.append(Path(os.environ["CABAL_DIR"]) / "store")
        home = Path.home()
        candidates += [home / ".cabal" / "store", home / ".local" / "state" / "cabal" / "store"]
        if ask_cabal:
            # The authoritative answer, for a store-dir set in cabal's configuration.
            try:
                out = subprocess.run(
                    ["cabal", "path", "--store-dir"], capture_output=True, text=True, check=True, timeout=120
                )
                candidates.insert(0, Path(out.stdout.strip()))
            except (OSError, subprocess.SubprocessError):
                pass
        return [c for c in candidates if c.is_dir()]

    def store_unit(self, unit_id: str) -> tuple[Path, Path]:
        for ask_cabal in (False, True):
            stores = self.stores(ask_cabal)
            for store in stores:
                for ghc_dir in sorted(store.glob(f"{self.compiler}*")):
                    unit_dir = ghc_dir / unit_id
                    if unit_dir.is_dir():
                        return unit_dir, ghc_dir / "package.db" / f"{unit_id}.conf"
        raise LicenceError(f"{unit_id} is not installed in any cabal store ({', '.join(map(str, stores))})")


def cabal_file(unit: dict) -> Path:
    directory = Path(unit["pkg-src"]["path"])
    files = sorted(directory.glob("*.cabal"))
    if len(files) != 1:
        raise LicenceError(f"{directory} holds {len(files)} .cabal files, not one")
    return files[0]


def cabal_field(path: Path, field: str) -> str | None:
    """A top-level field of a .cabal file, continuation lines joined."""
    lines = path.read_text().splitlines()
    for i, line in enumerate(lines):
        m = re.match(rf"^{re.escape(field)}\s*:\s*(.*)$", line, re.IGNORECASE)
        if m:
            value = [m.group(1).strip()]
            for more in lines[i + 1 :]:
                if more.startswith((" ", "\t")) and more.strip():
                    value.append(more.strip())
                else:
                    break
            return " ".join(v for v in value if v)
    return None


def conf_field(path: Path, field: str) -> str:
    if not path.is_file():
        raise LicenceError(f"no package registration at {path}")
    value = cabal_field(path, field)
    if not value:
        raise LicenceError(f"{path} has no {field} field")
    return value


def licence_files(directory: Path) -> list[Path]:
    found = {Path(p) for pattern in LICENCE_GLOBS for p in glob.glob(str(directory / pattern))}
    return sorted(p for p in found if p.is_file())


def join_texts(files: list[Path]) -> str:
    return "\n\n".join(f.read_text(errors="replace").strip("\n") for f in files) + "\n"


def normalise(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.strip().splitlines())


def spdx_ids(expressions) -> set[str]:
    ids: set[str] = set()
    for expression in expressions:
        ids |= set(re.findall(r"[A-Za-z0-9.+-]+", expression)) - {"AND", "OR", "WITH"}
    return ids


def read_expression(pyproject: Path) -> str:
    project = tomllib.loads(pyproject.read_text()).get("project", {})
    expression = project.get("license")
    if not isinstance(expression, str):
        raise SystemExit(f"wheel-licenses: {pyproject} has no SPDX licence expression in project.license")
    return expression


def render_sections(sections: dict[str, tuple[str, str]]) -> str:
    out = [HEADER]
    for key in sorted(sections, key=str.lower):
        spdx, text = sections[key]
        out += ["", RULE, f"{key} ({spdx})", RULE, "", text.strip("\n"), ""]
    return "\n".join(out)


def parse_sections(text: str) -> dict[str, tuple[str, str]]:
    sections: dict[str, tuple[str, str]] = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if lines[i] == RULE and i + 2 < len(lines) and lines[i + 2] == RULE:
            m = re.match(r"^(\S+) \((.*)\)$", lines[i + 1])
            if not m:
                raise LicenceError(f"malformed section header: {lines[i + 1]!r}")
            j = i + 3
            while j < len(lines) and not (lines[j] == RULE and j + 2 < len(lines) and lines[j + 2] == RULE):
                j += 1
            sections[m.group(1)] = (m.group(2), "\n".join(lines[i + 3 : j]).strip("\n") + "\n")
            i = j
        else:
            i += 1
    return sections


if __name__ == "__main__":
    sys.exit(main())
